-- =============================================================================
-- V1__create_core_schema.sql
-- ServiceOps Desk - Core schema (PostgreSQL 17)
-- Creates 6 core tables following the frozen Domain Model / ER design.
-- Conventions:
--   * Primary keys: BIGINT GENERATED BY DEFAULT AS IDENTITY
--   * Time fields:  TIMESTAMPTZ
--   * Enums:        VARCHAR + CHECK constraint (no PostgreSQL native ENUM)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. app_user
-- -----------------------------------------------------------------------------
CREATE TABLE app_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(64)  NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    display_name    VARCHAR(100) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    role            VARCHAR(32)  NOT NULL,
    status          VARCHAR(32)  NOT NULL,
    last_login_at   TIMESTAMPTZ  NULL,
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL,

    CONSTRAINT uk_app_user_username UNIQUE (username),
    CONSTRAINT uk_app_user_email    UNIQUE (email),
    CONSTRAINT ck_app_user_role CHECK (role IN ('REQUESTER', 'AGENT', 'MANAGER', 'ADMIN')),
    CONSTRAINT ck_app_user_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

-- -----------------------------------------------------------------------------
-- 2. sla_policy
-- -----------------------------------------------------------------------------
CREATE TABLE sla_policy (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(100) NOT NULL,
    priority           VARCHAR(16)  NOT NULL,
    response_minutes   INTEGER      NOT NULL,
    resolution_minutes INTEGER      NOT NULL,
    enabled            BOOLEAN      NOT NULL,
    created_at         TIMESTAMPTZ  NOT NULL,
    updated_at         TIMESTAMPTZ  NOT NULL,

    CONSTRAINT uk_sla_policy_priority UNIQUE (priority),
    CONSTRAINT ck_sla_policy_priority CHECK (priority IN ('P1_CRITICAL', 'P2_HIGH', 'P3_MEDIUM', 'P4_LOW')),
    CONSTRAINT ck_sla_policy_response_minutes   CHECK (response_minutes  > 0),
    CONSTRAINT ck_sla_policy_resolution_minutes CHECK (resolution_minutes > 0)
);

-- -----------------------------------------------------------------------------
-- 3. ticket  (aggregate root)
-- -----------------------------------------------------------------------------
CREATE TABLE ticket (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_no            VARCHAR(32)  NOT NULL,
    title                VARCHAR(200) NOT NULL,
    description          TEXT         NOT NULL,
    category             VARCHAR(64)  NOT NULL,
    priority             VARCHAR(16)  NOT NULL,
    status               VARCHAR(32)  NOT NULL,
    requester_id         BIGINT       NOT NULL,
    current_assignee_id  BIGINT       NULL,
    sla_policy_id        BIGINT       NOT NULL,
    response_due_at      TIMESTAMPTZ  NOT NULL,
    resolution_due_at    TIMESTAMPTZ  NOT NULL,
    first_responded_at   TIMESTAMPTZ  NULL,
    resolved_at          TIMESTAMPTZ  NULL,
    closed_at            TIMESTAMPTZ  NULL,
    escalation_level     INTEGER      NOT NULL DEFAULT 0,
    version              INTEGER      NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ  NOT NULL,
    updated_at           TIMESTAMPTZ  NOT NULL,

    CONSTRAINT uk_ticket_no UNIQUE (ticket_no),
    CONSTRAINT ck_ticket_priority CHECK (priority IN ('P1_CRITICAL', 'P2_HIGH', 'P3_MEDIUM', 'P4_LOW')),
    CONSTRAINT ck_ticket_status CHECK (status IN ('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'REOPENED')),
    CONSTRAINT ck_ticket_escalation_level CHECK (escalation_level >= 0),
    CONSTRAINT ck_ticket_version          CHECK (version >= 0),

    CONSTRAINT fk_ticket_requester         FOREIGN KEY (requester_id)        REFERENCES app_user (id),
    CONSTRAINT fk_ticket_current_assignee  FOREIGN KEY (current_assignee_id) REFERENCES app_user (id),
    CONSTRAINT fk_ticket_sla_policy        FOREIGN KEY (sla_policy_id)       REFERENCES sla_policy (id)
);

CREATE INDEX idx_ticket_requester        ON ticket (requester_id);
CREATE INDEX idx_ticket_current_assignee ON ticket (current_assignee_id);
CREATE INDEX idx_ticket_sla_policy       ON ticket (sla_policy_id);
CREATE INDEX idx_ticket_status           ON ticket (status);

-- -----------------------------------------------------------------------------
-- 4. ticket_assignment  (assignment history)
-- -----------------------------------------------------------------------------
CREATE TABLE ticket_assignment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id       BIGINT      NOT NULL,
    assignee_id     BIGINT      NOT NULL,
    assigned_by     BIGINT      NOT NULL,
    assignment_type VARCHAR(32) NOT NULL,
    assigned_at     TIMESTAMPTZ NOT NULL,
    ended_at        TIMESTAMPTZ NULL,
    created_at      TIMESTAMPTZ NOT NULL,

    CONSTRAINT ck_ticket_assignment_type CHECK (assignment_type IN ('ASSIGN', 'CLAIM', 'REASSIGN')),

    CONSTRAINT fk_ticket_assignment_ticket   FOREIGN KEY (ticket_id)   REFERENCES ticket (id),
    CONSTRAINT fk_ticket_assignment_assignee FOREIGN KEY (assignee_id) REFERENCES app_user (id),
    CONSTRAINT fk_ticket_assignment_by       FOREIGN KEY (assigned_by) REFERENCES app_user (id)
);

-- At most one ACTIVE (not-ended) assignment per ticket.
CREATE UNIQUE INDEX uk_ticket_assignment_active
    ON ticket_assignment (ticket_id)
    WHERE ended_at IS NULL;

CREATE INDEX idx_ticket_assignment_ticket   ON ticket_assignment (ticket_id);
CREATE INDEX idx_ticket_assignment_assignee ON ticket_assignment (assignee_id);

-- -----------------------------------------------------------------------------
-- 5. escalation
-- -----------------------------------------------------------------------------
CREATE TABLE escalation (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id        BIGINT       NOT NULL,
    level            INTEGER      NOT NULL,
    reason           VARCHAR(255) NOT NULL,
    trigger_type     VARCHAR(32)  NOT NULL,
    from_assignee_id BIGINT       NULL,
    to_assignee_id   BIGINT       NULL,
    triggered_at     TIMESTAMPTZ  NOT NULL,
    resolved_at      TIMESTAMPTZ  NULL,
    created_at       TIMESTAMPTZ  NOT NULL,

    CONSTRAINT ck_escalation_level CHECK (level > 0),
    CONSTRAINT ck_escalation_trigger_type CHECK (trigger_type IN ('SLA_RESPONSE_TIMEOUT', 'SLA_RESOLUTION_TIMEOUT', 'MANUAL')),

    CONSTRAINT fk_escalation_ticket         FOREIGN KEY (ticket_id)        REFERENCES ticket (id),
    CONSTRAINT fk_escalation_from_assignee  FOREIGN KEY (from_assignee_id) REFERENCES app_user (id),
    CONSTRAINT fk_escalation_to_assignee    FOREIGN KEY (to_assignee_id)   REFERENCES app_user (id)
);

CREATE INDEX idx_escalation_ticket ON escalation (ticket_id);

-- -----------------------------------------------------------------------------
-- 6. audit_log
-- NOTE: entity_id is a Polymorphic Reference (points to many entity types),
--       therefore NO foreign key is created on entity_id by design.
-- -----------------------------------------------------------------------------
CREATE TABLE audit_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type  VARCHAR(64)  NOT NULL,
    entity_id    BIGINT       NOT NULL,
    action       VARCHAR(64)  NOT NULL,
    actor_id     BIGINT       NULL,
    before_data  JSONB        NULL,
    after_data   JSONB        NULL,
    ip_address   VARCHAR(64)  NULL,
    created_at   TIMESTAMPTZ  NOT NULL,

    CONSTRAINT fk_audit_log_actor FOREIGN KEY (actor_id) REFERENCES app_user (id)
);

CREATE INDEX idx_audit_log_actor      ON audit_log (actor_id);
CREATE INDEX idx_audit_log_entity     ON audit_log (entity_type, entity_id);
CREATE INDEX idx_audit_log_created_at ON audit_log (created_at);
