spring:
  application:
    name: serviceops-backend

  config:
    import: optional:file:../config/application-local.yml

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info